[package]
name = "zephyrvox-voice"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aes-gcm.workspace = true
bytes.workspace = true
hkdf.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeroize.workspace = true
zephyrvox-types = { path = "../zephyrvox-types" }
zephyrvox-wire = { path = "../zephyrvox-wire" }
