use zephyrvox_types::{SessionId, Snowflake, StreamTypeId, VoiceEndpoint};
use zephyrvox_voice::{PacketCodec, SessionKey, VoiceSessionConfig};

// The expected bytes are generated by CommunityServer's
// internal/protocol.EncodePacket after HKDF direction-key derivation. This
// test intentionally does not use the Rust encoder to create its fixture.
fn go_vector_config() -> VoiceSessionConfig {
    let session_id = SessionId::parse_hex("000102030405060708090a0b0c0d0e0f").expect("id");
    let key = SessionKey::from_bytes(std::array::from_fn(|index| index as u8));
    VoiceSessionConfig::new(
        VoiceEndpoint {
            host: "127.0.0.1".to_owned(),
            port: 40_100,
        },
        session_id,
        true,
        1_142,
        1_800_000_000_000,
        Some(key),
    )
    .expect("config")
    .with_stream_types([StreamTypeId::new(1), StreamTypeId::new(2)])
    .expect("streams")
}

fn decode_hex(value: &str) -> Vec<u8> {
    let value = value.trim();
    assert_eq!(value.len() % 2, 0, "odd hex fixture length");
    value
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let high = char::from(pair[0]).to_digit(16).expect("hex digit");
            let low = char::from(pair[1]).to_digit(16).expect("hex digit");
            ((high << 4) | low) as u8
        })
        .collect()
}

#[test]
fn go_c2s_vector_matches_rust_codec_and_decodes() {
    let codec = PacketCodec::from_config(&go_vector_config(), None).expect("codec");
    let expected = decode_hex(include_str!("fixtures/go_encrypted_c2s.hex"));
    let actual = codec
        .encode_media(9, 0x4242, StreamTypeId::new(1), b"encrypted opus")
        .expect("packet");

    assert_eq!(actual, expected);
    let decoded = codec.decode_client(&expected).expect("decode");
    assert_eq!(decoded.transport_seq, 9);
    assert_eq!(decoded.channel_seq, 0x4242);
    assert_eq!(decoded.stream_type, StreamTypeId::new(1));
    assert_eq!(decoded.payload, b"encrypted opus".as_slice());
}

#[test]
fn go_s2c_vector_matches_rust_codec_and_decodes() {
    let codec = PacketCodec::from_config(&go_vector_config(), None).expect("codec");
    let expected = decode_hex(include_str!("fixtures/go_encrypted_s2c.hex"));
    let speaker = Snowflake::new(42).expect("speaker");
    let actual = codec
        .encode_server_media(4, 0x1234, StreamTypeId::new(2), speaker, b"relay")
        .expect("packet");

    assert_eq!(actual, expected);
    let decoded = codec.decode_server(&expected).expect("decode");
    assert_eq!(decoded.transport_seq, 4);
    assert_eq!(decoded.channel_seq, 0x1234);
    assert_eq!(decoded.speaker_id, Some(speaker));
    assert_eq!(decoded.stream_type, StreamTypeId::new(2));
    assert_eq!(decoded.payload, b"relay".as_slice());
}
